version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: npm test
      - run: npm build
