version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:14-browsers

jobs:
  unit_test:
    executor: my-executor
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: npm install

      - run:
          name: "Running unit test"
          command: npm run citest:coverage:unit

  integration_test:
    executor: my-executor
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: npm install

      - run:
          name: "Running integration test"
          command: npm run citest:coverage:integration

  build_app:
    executor: my-executor
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Building app"
          command: npm run build

workflows:
  tests:
    jobs:
      - unit_test
      - integration_test
  build:
    jobs:
      - build_app
